# Generated by Django 4.2.1 on 2023-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_variant_variant_name'),
        ('carts', '0002_rename_product_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='user.variant'),
        ),
    ]
