# Generated by Django 4.2.1 on 2023-05-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
