# Generated by Django 4.2.1 on 2023-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_image_remove_product_images_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
