# Generated by Django 4.2.1 on 2023-05-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_product_stock_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
