# Generated by Django 4.2.1 on 2023-05-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_product_stock_image_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='variant',
        ),
    ]
