# Generated by Django 4.2.1 on 2023-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_image_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
