# Generated by Django 4.2.1 on 2023-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_variant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_name',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=200),
        ),
    ]
