# Generated by Django 4.2.1 on 2023-05-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_variant_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_name',
            field=models.CharField(max_length=200),
        ),
    ]
