# Generated by Django 4.2.1 on 2023-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_variant_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variation_category',
            field=models.CharField(default='size', max_length=100),
        ),
    ]
