# Generated by Django 4.2.1 on 2023-05-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_variant_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variation_category',
        ),
    ]
