# Generated by Django 4.2.1 on 2023-06-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_select_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='select_address',
            new_name='selected_address',
        ),
    ]
